### ISSUE TITLE
TLS configs

### ISSUE THREAD

**Issue by mahsamcse** [Epodonios/v2ray-configs#11]
با درود
ضمن تشکر از زحمات بی نظیر شما
ممنون میشم یک لینک و دسته بندی جدا هم درست کنید برای کانفیگ های TLS دار
تا اگه دوستانی امنیت بالاتری نیاز دارن راحت تر بتونن استفاده کنن - چون تعداد کانفیگ ها زیاده و اسکرول کردن کمی مشکله و البته از طرفی استفاده در اپ هایی مثل هیدیفای که خودکار به بهترین پینگ وصل میشن عملا نمیشه فقط از TLS دارها استفاده کرد
ممنون

**Comment by Mehybinator** [comment]
سلام @mahsamcse ,اضافه کردم صبر کن صاحب ریپازیتوری قبولش کنه.

**Comment by Epodonios** [comment]
> سلام @mahsamcse ,اضافه کردم صبر کن صاحب ریپازیتوری قبولش کنه.

Tnx

**Comment by Epodonios** [comment]
Fixed
