### ISSUE TITLE
Stealing people's labor?! 

### ISSUE THREAD

**Issue by erfjab** [Epodonios/v2ray-configs#4]
After examining the source code, it appears that you have downloaded and used the configurations of the original project, but under your own name to draw attention to your project! If my assumption is incorrect, please clarify so I can apologize, but if it is accurate, I urge you to collaborate through your own efforts. This action undermines both the open-source community and your reputation. While such misuse is unfortunately not uncommon, I still wish you success.

**Comment by erfjab** [comment]
GitHub link of the project that has been used:

https://github.com/yebekhe/TelegramV2rayCollector

**Comment by Epodonios** [comment]
> After examining the source code, it appears that you have downloaded and used the configurations of the original project, but under your own name to draw attention to your project! If my assumption is incorrect, please clarify so I can apologize, but if it is accurate, I urge you to collaborate through your own efforts. This action undermines both the open-source community and your reputation. While such misuse is unfortunately not uncommon, I still wish you success.

Hi bro 
yebekhe's script is public for anybody can use and edit it

let me tell u something dont use g translate any more
